name: DeepDSI
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.7.0
  - pip=21.2.2
  - cudatoolkit=11.3.1
  - pytorch=1.10.1
  - h5py=3.5.0
  - matplotlib=3.5.0
  - numpy=1.21.2
  - pandas=1.3.4
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - seaborn=0.11.2
  - tqdm=4.62.3
  - pip:
    - torch-geometric==2.0.3
    - torch-scatter==2.0.9
    - torch-sparse==0.6.12